version: "{build}"

stack: python 3.10.0

environment:
  matrix:
  # For regular jobs, such as push, pr and etc.
  - job_name: Linux
    appveyor_build_worker_image: ubuntu1804
    GOARCH: amd64

for: 
  - # Linux
    build: off
    matrix:
      only:
        - job_name: Linux
    branches:
      only:
        - master
    deploy:
      - provider: script
        on:
          branch: master
    before_deploy:
      - make deploy
    deploy_script:
      - echo "Completed!"
