version: "{build}"

environment:
  matrix:
  # For regular jobs, such as push, pr and etc.
  - job_name: Linux
    appveyor_build_worker_image: ubuntu1804
    GOARCH: amd64
  # - job_name: MacOS
  #   appveyor_build_worker_image: macos-bigsur
  #   GOARCH: amd64
  # - job_name: Windows
  #   appveyor_build_worker_image: Visual Studio 2019
  #   GOARCH: amd64

for:
  # - # Windows
  #     build: off
  #     matrix:
  #       only:
  #         - job_name: Windows
  #     branches:
  #       only:
  #         - master
  #     install:
  #       - choco install make
  #     deploy:
  #       - provider: script
  #         on:
  #           branch: master
  #     build_script:
  #       - make deploy 
  
  - # Linux
      build: off
      matrix:
        only:
          - job_name: Linux
      branches:
        only:
          - master
      deploy:
        - provider: script
          on:
            branch: master
      build_script:
        - make deploy
  
  # - # MacOS
  #     build: off
  #     matrix:
  #       only:
  #         - job_name: MacOS
  #     branches:
  #       only:
  #         - master
  #     deploy:
  #       - provider: script
  #         on:
  #           branch: master
  #     build_script:
  #       - make deploy