version: "{build}"

stack: python 3.10.0

environment:
  matrix:
  # For regular jobs, such as push, pr and etc.
  - job_name: Linux
    appveyor_build_worker_image: ubuntu1804
    GOARCH: amd64

for: 
  - # Linux
    build: off
    matrix:
      only:
        - job_name: Linux

    install:
      - sudo apt update
      - sudo apt install mkdocs
    branches:
      only:
        - main
    deploy:
      - provider: script
        on:
          branch: main
    before_deploy:
      - make deploy
    deploy_script:
      - echo "Completed!"
